

const FormConstants = {

	SELECTED_OPTION_REQUEST: 'SELECTED_OPTION_REQUEST',
	SELECTED_OPTION_SUCCESS: 'SELECTED_OPTION_SUCCESS',
	SELECTED_OPTION_FAILED: 'SELECTED_OPTION_FAILED'
}



export default FormConstants