

const GoogleConstants = {

	GOOGLE_AUTH_PREPARE_REQUEST : 'GOOGLE_AUTH_PREPARE_REQUEST',
	GOOGLE_AUTH_PREPARE_SUCCESS : 'GOOGLE_AUTH_PREPARE_SUCCESS',
	GOOGLE_AUTH_PREPARE_FAILURE : 'GOOGLE_AUTH_PREPARE_FAILURE',


	GOOGLE_LOGIN_REQUEST : 'GOOGLE_LOGIN_REQUEST',
	GOOGLE_LOGIN_SUCCESS : 'GOOGLE_LOGIN_SUCCESS',
	GOOGLE_LOGIN_FAILURE : 'GOOGLE_LOGIN_FAILURE',


	GOOGLE_CONTACTS_REQUEST : 'GOOGLE_CONTACTS_REQUEST',
	GOOGLE_CONTACTS_SUCCESS : 'GOOGLE_CONTACTS_SUCCESS',
	GOOGLE_CONTACTS_FAILURE : 'GOOGLE_CONTACTS_FAILURE',

	GOOGLE_SIGNOUT_REQUEST: 'GOOGLE_SIGNOUT_REQUEST',
	GOOGLE_SIGNOUT_SUCCESS: 'GOOGLE_SIGNOUT_SUCCESS',
	GOOGLE_SIGNOUT_FAILURE: 'GOOGLE_SIGNOUT_FAILURE',

	GOOGLE_PROFILE_REQUEST: 'GOOGLE_PROFILE_REQUEST',
	GOOGLE_PROFILE_SUCCESS: 'GOOGLE_PROFILE_SUCCESS',
	GOOGLE_PROFILE_FAILURE: 'GOOGLE_PROFILE_FAILURE'

}



export default GoogleConstants