

const IdentityConstants = {

	IDENTITY_REDIRECT_SUCCESS: 'IDENTITY_REDIRECT_SUCCESS',

	IDENTITY_LOGIN_REQUEST: 'IDENTITY_LOGIN_REQUEST',
	IDENTITY_LOGIN_SUCCESS: 'IDENTITY_LOGIN_SUCCESS',
	IDENTITY_LOGIN_FAILURE: 'IDENTITY_LOGIN_FAILURE',

	IDENTITY_REGISTER_REQUEST: 'IDENTITY_REGISTER_REQUEST',
	IDENTITY_REGISTER_SUCCESS: 'IDENTITY_REGISTER_SUCCESS',
	IDENTITY_REGISTER_FAILURE:'IDENTITY_REGISTER_FAILURE',

	IDENTITY_ISSIGNEDIN_REQUEST: 'IDENTITY_ISSIGNEDIN_REQUEST',
	IDENTITY_ISSIGNEDIN_SUCCESS: 'IDENTITY_ISSIGNEDIN_SUCCESS',
	IDENTITY_ISSIGNEDIN_FAILURE: 'IDENTITY_ISSIGNEDIN_FAILURE',

	IDENTITY_BTW_USERPROFILE_REQUEST: 'IDENTITY_BTW_USERPROFILE_REQUEST',
	IDENTITY_BTW_USERPROFILE_SUCCESS: 'IDENTITY_BTW_USERPROFILE_SUCCESS',
	IDENTITY_BTW_USERPROFILE_FAILURE: 'IDENTITY_BTW_USERPROFILE_FAILURE',

	IDENTITY_MAKELIST_PERSIST: 'IDENTITY_MAKELIST_PERSIST'
}

export default IdentityConstants