export default {
    register: '/captainProfile/Register',
    makelist: '/captainProfile/MakeList',
    pageDown: '/errorPages/Page_50_X',
    invites: '/invites/SendInvite',
    tasksList: '/tasksList',
    voterList: '/voterList',
    community: '/community',
    captainsDashboard: '/captainsDashboard',
    adminDashboard: '/adminDashboard',
    login: '/',
    voterDetail: '/voterDetail',
    matchList: '/matchList',
    voterSuccess: '/voterSuccess',
    voterError: '/voterError',
    forum: '/forum',
    reports: '/reports',
    addVoterTask: '/task/addVoters',
    literatureTextTask: '/task/literatureText',
    literatureVideoTask: '/task/literatureVideo',
    recruitingCaptainTask: '/task/recruitingCaptains',
    registerVoterTask: '/task/registerVoters',
    updateProfileTask: '/task/updateProfile',
    // static pages
    whyBetheWave: '/whyBetheWave',
    howContribute: '/howYouCanContribute'
}
