const VoterContants = {
	VOTER_MAKELIST_PERSIST: 'VOTER_MAKELIST_PERSIST',
	VOTER_DETAILS_PERSIST: 'VOTER_DETAILS_PERSIST',
	VOTER_NEXT_MUMBER_PERSIST: 'VOTER_NEXT_MUMBER_PERSIST',
	VOTER_MATCHLIST_PERSIST: 'VOTER_MATCHLIST_PERSIST',
	VOTER_RESET_STATE: 'VOTER_RESET_STATE',
	VOTERS_COUNT: 4,
	FIRST_NAME_PREIX: 'firstname',
	LAST_NAME_PREFIX: 'lastname',
	VOTER_LIST_REQUEST: 'VOTER_LIST_REQUEST',
	VOTER_LIST_SUCCESS: 'VOTER_LIST_SUCCESS',
	VOTER_LIST_ERROR: 'VOTER_LIST_ERROR',
	VOTER_UPDATE_SUCCESS: 'VOTER_UPDATE_SUCCESS',
	VOTER_UPDATE_ERROR: 'VOTER_UPDATE_ERROR'
};

export default VoterContants