const VoterContants = {
	VOTER_MAKELIST_PERSIST: 'VOTER_MAKELIST_PERSIST',
	VOTER_DETAILS_PERSIST: 'VOTER_DETAILS_PERSIST',
	VOTER_NEXT_MUMBER_PERSIST: 'VOTER_NEXT_MUMBER_PERSIST',
	VOTER_MATCHLIST_PERSIST: 'VOTER_MATCHLIST_PERSIST',
	VOTER_RESET_STATE: 'VOTER_RESET_STATE',
	VOTERS_COUNT: 4
};

export default VoterContants